language: ruby

script:
  - bundle exec jekyll build --baseurl=/weinerlabsite

deploy:
  provider: pages
  local-dir: _site/
  verbose: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master

sudo: false
